ravindersingh@CS-RAVINSING-LT:~/ms-java-common/Infra/kubernetes$ cat ms-java-common-deployment.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-sidecar-ms-java-common
  namespace: dev
  labels:
    app: ms-java-common
    component: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        paths:
          - "/var/log/*.log"
        fields_under_root: true
        tags: ENVIRONMENT-common
        multiline:
          pattern: '^\S.*[0-9]{1,4}-[0-9]{2}-[0-9]{2,4}'
          negate: true
          match: after
          max_lines: 500
        fields:
          type: cc
          app_id: ENVIRONMENT-common
    output:
      logstash:
        hosts: ["ELKHOST"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-java-common
  namespace: dev
  labels:
    app: ms-java-common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-java-common
  template:
    metadata:
      labels:
        app: ms-java-common
    spec:
      containers:
        - name: ms-java-common
          image: ms-java-common:local
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_ADDR
              value: "http://192.168.80.140:8200"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: token
          ports:
            - containerPort: 8100
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8100
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: filebeat-logs
              mountPath: /var/log

        - name: filebeat-sidecar
          image: docker.elastic.co/beats/filebeat:7.5.0
          volumeMounts:
            - name: filebeat-logs
              mountPath: /var/log
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml

      volumes:
        - name: filebeat-logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-sidecar-ms-java-common
            items:
              - key: filebeat.yml
                path: filebeat.yml

      imagePullSecrets:
        - name: my-secret-docker-pass

---
apiVersion: v1
kind: Service
metadata:
  name: ms-java-common-service
  namespace: dev
  labels:
    app: ms-java-common
spec:
  type: ClusterIP
  selector:
    app: ms-java-common
  ports:
    - name: http
      port: 8100
      targetPort: 8100
  sessionAffinity: ClientIP
