healthcheck.version.table.name=com_version
healthcheck.app.name.alias=COMMON
healthcheck.app.name=Common Micro Service
healthcheck.app.version=2.0.0

# Should be false if application doesn't have any DB integration
healthcheck.include.db=true

# # Should be false if application doesn't have any AMQP integration
healthcheck.include.amqp=false
